name: DeltaRedis
main: com.gmail.tracebachi.DeltaRedis.Spigot.DeltaRedis
version: ${project.version}
author: Trace Bachi (tracebachi@gmail.com, BigBossZee)
commands:
  deltaredisdebug:
    description: Allows the user to toggle debug logging for DeltaRedis.
    aliases: []
  isonline:
    description: Allows the user to check if a player is online.
    aliases: [find]
  runcmd:
    description: Allows the user to send commands to other servers that will get run by that server's console.
    aliases: [rc]
permissions:
  DeltaRedis.Debug:
    description: Permission to use /deltaredisdebug
  DeltaRedis.IsOnline:
    description: Permission to use /isonline
  DeltaRedis.RunCmd:
    description: Permission to use /runcmd
